---
Name: sqs_config
---
Symbiote\SqsJobQueue\Service\SqsService:
  default_tasks: null
Symbiote\QueuedJobs\Controllers\QueuedJobsAdmin:
  extensions:
    - Symbiote\SqsJobQueue\Extension\SqsQueuedJobExtension
SilverStripe\Core\Injector\Injector:
  SqsScheduleRunnerJob:
    class: Symbiote\SqsJobQueue\Job\SqsScheduleRunnerJob
    properties:
      queuedJobService: '%$Symbiote\QueuedJobs\Services\QueuedJobService'
      sqsService: '%$Symbiote\SqsJobQueue\Service\SqsService'
  SqsClient:
    factory: Symbiote\SqsJobQueue\Service\SqsClientFactory
  QueuedJobRunner:
    class: Symbiote\SqsJobQueue\Service\QueuedJobRunner
    properties:
      queuedJobService: '%$Symbiote\QueuedJobs\Services\QueuedJobService'
  Symbiote\SqsJobQueue\Service\SqsService:
    properties:
      client: '%$SqsClient'
      handlers:
        runJob: '%$QueuedJobRunner'
        processScheduledJobs: '%$SqsScheduleRunnerJob'
      defaultTasks:
        SqsScheduleRunnerJob: processScheduledJobs
